name: v_6dgs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - tqdm
  - requests
  - plyfile
  - pip:
    - opencv-python